//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartServices.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetails
    {
        public int Item_Id { get; set; }
        public string Item_Name { get; set; }
        public Nullable<decimal> Item_Price { get; set; }
        public string Image_Name { get; set; }
    }
}
